//! Shared PostgreSQL Component/Integration test harness (`docs/development/testing.md`
//! "Test isolation": "isolated databases", "explicit setup and teardown").
//!
//! Every test gets its own uniquely named database, migrated through the
//! real Adapter's own `adapters::postgres::connect` entry point — never a
//! hand-rolled schema shortcut, so these tests exercise exactly the
//! migration path the running Server uses.
//!
//! Requires a real, reachable PostgreSQL instance (ADR-0013). The admin
//! connection used to create/drop each per-test database defaults to
//! `postgres://postgres@localhost:5432/postgres` — this machine's local,
//! trust-authenticated development instance — and can be overridden with
//! `BAMEP_TEST_PG_ADMIN_URL` for other environments. No production
//! credential is hardcoded; every database this harness creates or drops
//! carries the `bamep_wp1_test_` prefix it generates itself, so teardown
//! never touches a database this harness did not itself create.

use sqlx::PgPool;
use uuid::Uuid;

fn admin_url() -> String {
    std::env::var("BAMEP_TEST_PG_ADMIN_URL")
        .unwrap_or_else(|_| "postgres://postgres@localhost:5432/postgres".to_string())
}

fn with_database(url: &str, db_name: &str) -> String {
    let (prefix, _existing_db) = url
        .rsplit_once('/')
        .expect("admin URL must include a database path segment");
    format!("{prefix}/{db_name}")
}

pub struct TestDatabase {
    pub pool: PgPool,
    pub db_url: String,
    name: String,
    admin_url: String,
}

impl TestDatabase {
    /// Creates a uniquely named, `bamep_wp1_test_`-prefixed database and
    /// applies every WP1 migration to it via the real Adapter connect path.
    pub async fn setup() -> Self {
        let admin_url = admin_url();
        let name = format!("bamep_wp1_test_{}", Uuid::new_v4().simple());

        let admin_pool = PgPool::connect(&admin_url).await.unwrap_or_else(|e| {
            panic!(
                "connect to PostgreSQL admin database at {admin_url} \
                 (override with BAMEP_TEST_PG_ADMIN_URL): {e}"
            )
        });
        // `name` is generated by this harness (UUID-based), never external
        // input — `AssertSqlSafe` documents that audit, it does not bypass
        // it (sqlx::query normally requires a `&'static str` literal).
        sqlx::query(sqlx::AssertSqlSafe(format!(r#"CREATE DATABASE "{name}""#)))
            .execute(&admin_pool)
            .await
            .expect("create per-test database");
        admin_pool.close().await;

        let db_url = with_database(&admin_url, &name);
        let pool = bamep_server::adapters::postgres::connect(&db_url)
            .await
            .expect("connect to and migrate the fresh per-test database");

        Self {
            pool,
            db_url,
            name,
            admin_url,
        }
    }

    /// Closes this test's pool and drops its database. Rust has no async
    /// `Drop`, so every test must call this explicitly; a test that panics
    /// before reaching it leaves behind a `bamep_wp1_test_*`-prefixed
    /// database only — trivially identifiable, never a production or
    /// owner-owned database, and safe to reap separately.
    pub async fn teardown(self) {
        self.pool.close().await;
        let admin_pool = PgPool::connect(&self.admin_url)
            .await
            .expect("connect to PostgreSQL admin database for teardown");
        sqlx::query(sqlx::AssertSqlSafe(format!(
            r#"DROP DATABASE IF EXISTS "{}" WITH (FORCE)"#,
            self.name
        )))
        .execute(&admin_pool)
        .await
        .expect("drop per-test database");
        admin_pool.close().await;
    }
}
